### PR TITLE
Docker setup

### PR DESCRIPTION
**Pull request by PerkinsDan**
Closes # 

## 📑 Description

Added docker compose to allow for easy devlopment env setup

- To start do docker compose up

It can take time the first time so be patient

## ✅ Checks

- [X] My pull request adheres to the code style of this project
- [X] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [X] All the tests have passed

### CODE REVIEW

**Comment by PerkinsDan** [comment]
@MichaelVoropanov Before PR please compose on your system to check since we don't have tests yet

**Comment by MichaelVoropanov** [comment]
image

**Comment by MichaelVoropanov** [comment]
```
ossf     |
ossf     | > ossf-aperta@0.1.0 dev:docker
ossf     | > cp ./.env.docker ./.env && next dev
ossf     |
ossf     | sh: 1: next: not found
ossf exited with code 127
```

**Comment by MichaelVoropanov** [comment]
Might be a bug with my docker working on it.

**Comment by MichaelVoropanov** [comment]
Working now `next was not installed` (It was bugged) rebooted and it now works.

**Pull request merged**
